players: {}
locations:
  oberstadt:
    world: world
    x: 100
    y: 80
    z: 100

  unterstadt:
    world: world
    x: -50
    y: 40
    z: -120
sanctum:
  world: world
  x: 300
  y: 120
  z: 300

